version: "3.7"

services:
  kong-migration:
    image: ${LFH_KONG_IMAGE}
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: ${LFH_KONG_DATABASE_TYPE}
      KONG_PG_HOST: postgres
      KONG_PG_USER: ${LFH_PG_USER}
      KONG_PG_PASSWORD: ${LFH_PG_PASSWORD}
    command: kong migrations bootstrap -v
